CL_OK = 0x00

CL_ERR_NO_MEMORY = 0x01

CL_ERR_INVALID_PARAMETER = 0x02

CL_ERR_NULL_POINTER = 0x03

CL_ERR_NOT_EXIST = 0x04

CL_ERR_INVALID_HANDLE = 0x05

CL_ERR_INVALID_BUFFER = 0x06

CL_ERR_NOT_IMPLEMENTED = 0x07

CL_ERR_DUPLICATE = 0x08

CL_ERR_QUEUE_NOT_AVAILABLE = 0x09

CL_ERR_OUT_OF_RANGE = 0x0a

CL_ERR_NO_RESOURCE = 0x0b

CL_ERR_INITIALIZED = 0x0c

CL_ERR_BUFFER_OVERRUN = 0x0d

CL_ERR_NOT_INITIALIZED = 0x0e

CL_ERR_VERSION_MISMATCH = 0x0f

CL_ERR_ALREADY_EXIST = 0x10

CL_ERR_UNSPECIFIED = 0x11

CL_ERR_INVALID_STATE = 0x12

CL_ERR_DOESNT_EXIST = 0x13

CL_ERR_TIMEOUT = 0x14

CL_ERR_INUSE = 0x15

CL_ERR_TRY_AGAIN = 0x16

CL_ERR_NO_CALLBACK = 0x17

CL_ERR_MUTEX_ERROR = 0x18

CL_ERR_NO_OP = 0x19

CL_ERR_NAME_TOO_LONG = 0x1a

CL_ERR_NAME_NOT_FOUND = 0x1b

CL_ERR_MESSAGE_ERROR = 0x1c

CL_ERR_TOO_BIG = 0x1d

CL_ERR_NO_SECTIONS = 0x1e

CL_ERR_FAILED_OPERATION = 0x1f

CL_ERR_OP_NOT_PERMITTED = 0x20

CL_ERR_NO_SPACE = 0x21

CL_ERR_BAD_FLAG = 0x22

CL_ERR_BAD_OPERATION = 0x23

CL_ERR_LIBRARY = 0x24

CL_ERR_NOT_SUPPORTED = 0x25

CL_ERR_INTERRUPT = 0x26

CL_ERR_CONTINUE = 0x27

CL_ERR_COMMON_MAX = 0xff

CL_CID_OFFSET = 16

CL_ERROR_CODE_MASK = 0xffff

def CL_RC(CID, ERROR_CODE):
    _cid = CID.value
    _error_code = ERROR_CODE.value

    return _error_code if _error_code == CL_OK else (_cid << CL_CID_OFFSET) | (_error_code & CL_ERROR_CODE_MASK)

def CL_GET_ERROR_CODE(RC):
    _rc = RC.value
    return _rc & CL_ERROR_CODE_MASK

def CL_GET_CID(RC):
    _rc = RC.value
    return _rc >> CL_CID_OFFSET
