CL_VERSION_SHIFT = 24
CL_VERSION_MASK = (1 << CL_VERSION_SHIFT) - 1

CL_RELEASE_VERSION_BASE = 4 
CL_MAJOR_VERSION_BASE = 0
CL_MINOR_VERSION_BASE = 0

CL_RELEASE_VERSION = 4
CL_MAJOR_VERSION = 0
CL_MINOR_VERSION = 0

CL_RELEASE_VERSION_CURRENT = 6
CL_MAJOR_VERSION_CURRENT = 0
CL_MINOR_VERSION_CURRENT = 0

def CL_VERSION_CODE(rel, major, minor):
    return (rel << 16) | (major << 8) | minor

CL_VERSION_CURRENT = CL_VERSION_CODE(CL_RELEASE_VERSION_CURRENT, CL_MAJOR_VERSION_CURRENT, CL_MINOR_VERSION_CURRENT)

def CL_VERSION_RELEASE(version):
    return (version >> 16) & 0xff

def CL_VERSION_MAJOR(version):
    return (version >> 8 ) & 0xff

def CL_VERSION_MINOR(version):
    return version & 0xff
