import sys
sys.path.append("..")

from common import clCommon, clCommonErrors

CL_IOC_ERR_INIT_FAILED = 0x100
CL_IOC_ERR_COMMPORT_REG_FAIL = 0x101
CL_IOC_ERR_TRY_AGAIN = 0x102
CL_IOC_ERR_COMMPORT_INVALID_MODE = 0x103
CL_IOC_ERR_TL_LIMIT_EXCEEDED = 0x104
CL_IOC_ERR_TL_DUPLICATE_ENTRY = 0x105
CL_IOC_ERR_TL_ACTIVE_INST_NOT_PRESENT = 0x106
CL_IOC_ERR_INVALID_SESSION = 0x107
CL_IOC_ERR_COMP_UNREACHABLE = 0x108
CL_IOC_ERR_XPORT_NOT_REGISTERED = 0x109
CL_IOC_ERR_XPORT_ALREADY_REGISTERED = 0x10a
CL_IOC_ERR_XPORT_LINK_NOT_REGISTERED = 0x10b
CL_IOC_ERR_XPORT_LINK_NOT_DELETED = 0x10c
CL_IOC_ERR_HOST_UNREACHABLE = 0x10d
CL_IOC_ERR_COMMPORT_BLOCKED = 0x10e
CL_IOC_ERR_ROUTE_NOT_EXIST = 0x10f
CL_IOC_ERR_PROTO_IN_USE_WITH_IOC = 0x110
CL_IOC_ERR_FLOW_XOFF_STATE = 0x111
CL_IOC_ERR_RECV_UNBLOCKED = 0x112
CL_IOC_ERR_INVALID_MSG_OPTION = 0x113
CL_IOC_ERR_XPORT_LINK_LIMIT_EXCEEDED = 0x114
CL_IOC_ERR_NODE_EXISTS = 0x115
CL_IOC_ERR_MAX = 0x116

def CL_IOC_RC(ERROR_CODE):
    return clCommonErrors.CL_RC(clCommon.eClCompIdT.CL_CID_IOC, ERROR_CODE)
