CL_IOC_MAX_NODES = 1024
CL_IOC_MIN_NODE_ADDRESS = 1
CL_IOC_MAX_NODE_ADDRESS = CL_IOC_MAX_NODES - 1

CL_IOC_MAX_COMPONENTS_PER_NODE = 1024
CL_IOC_MIN_COMP_PORT = 1
CL_IOC_MAX_COMP_PORT = CL_IOC_MAX_COMPONENTS_PER_NODE - 1

CL_IOC_RESERVED_PORTS = 64
CL_IOC_USER_RESERVED_PORTS = 64
CL_IOC_EPHEMERAL_PORTS = CL_IOC_MAX_COMPONENTS_PER_NODE - CL_IOC_RESERVED_PORTS - CL_IOC_USER_RESERVED_PORTS
CL_IOC_REASSEMBLY_TIMEOUT = 5000
