import sys
sys.path.append("..")

from common import clCommonErrors, clCommon

def CL_EVENTS_RC(ERROR_CODE):
    return clCommonErrors.CL_RC(clCommon.eClCompIdT.CL_CID_EVENTS, ERROR_CODE)

CL_EVENT_ERR_INIT_NOT_DONE = 0x100
CL_EVENT_ERR_INTERNAL = 0x101
CL_EVENT_ERR_INVALID_PARAM = 0x102
CL_EVENT_ERR_BAD_FLAGS = 0x103
CL_EVENT_ERR_INVALID_CHANNEL_HANDLE = 0x104
CL_EVENT_ERR_BAD_HANDLE = 0x105
CL_EVENT_ERR_NO_MEM = 0x106
CL_EVENT_ERR_NULL_PTR = 0x107
CL_EVENT_ERR_CHANNEL_ALREADY_OPENED = 0x108
CL_EVENT_ERR_CHANNEL_NOT_OPENED = 0x109
CL_EVENT_ERR_DUPLICATE_SUBSCRIPTION = 0x10a
CL_EVENT_ERR_NOT_OPENED_FOR_SUBSCRIPTION = 0x10b
CL_EVENT_ERR_NOT_OPENED_FOR_PUBLISH = 0x10c
CL_EVENT_ERR_INFO_WALK_STOP = 0x10d
CL_EVENT_ERR_ALREADY_INITIALIZED = 0x10e
CL_EVENT_ERR_STOP_WALK = 0x10f
CL_EVENT_ERR_NO_SPACE = 0x110
CL_EVENT_ERR_VERSION = 0x111
CL_EVENT_ERR_EXIST = 0x112
CL_EVENT_ERR_NO_RESOURCE = 0x113
CL_EVENT_ERR_INIT = 0x114
