import clUtils
import saAis

ClIocNotificationIdT = saAis.SaInt32T
class eClIocNotificationIdT(clUtils.CEnum):
    CL_IOC_NODE_ARRIVAL_NOTIFICATION = 0,
    CL_IOC_NODE_LEAVE_NOTIFICATION = 1,
    CL_IOC_COMP_ARRIVAL_NOTIFICATION = 2,
    CL_IOC_COMP_DEATH_NOTIFICATION = 3,
    CL_IOC_SENDQ_WM_NOTIFICATION = 4,
    CL_IOC_COMM_PORT_WM_NOTIFICATION = 5,
    CL_IOC_LOG_NOTIFICATION = 6,
    CL_IOC_NODE_VERSION_NOTIFICATION = 7,
    CL_IOC_NODE_VERSION_REPLY_NOTIFICATION = 8,
    CL_IOC_NODE_DISCOVER_NOTIFICATION = 9,
    CL_IOC_NODE_LINK_UP_NOTIFICATION = 10,
    CL_IOC_NODE_LINK_DOWN_NOTIFICATION = 11,
    CL_IOC_NODE_DISCOVER_PEER_NOTIFICATION = 12
