import sys
sys.path.append("..")

from common import clCommonErrors, clCommon

def CL_EO_RC(ERROR_CODE):
    return clCommonErrors.CL_RC(clCommon.eClCompIdT.CL_CID_EO, ERROR_CODE)

CL_EO_ERR_EO_SUSPENDED = 0x101
CL_EO_ERR_FUNC_NOT_REGISTERED = 0x102
CL_EO_ERR_INVALID_CLIENTID = 0x103
CL_EO_ERR_INVALID_SERVICEID = 0x104
CL_EO_ERR_LIB_ID_INVALID = 0x105
CL_EO_ERR_WATER_MARK_ID_INVALID = 0x106
CL_EO_ERR_IMPROPER_STATE = 0x107
CL_EO_ERR_QUEUE_OVERFLOW = 0x108
CL_EO_ERR_ENQUEUE_MSG = 0x109
