import sys
sys.path.append("..")

from common import clCommon, clCommonErrors

CL_AMS_ERR_INVALID_COMP = 0x100    

CL_AMS_ERR_INVALID_ENTITY = 0x101

CL_AMS_ERR_INVALID_ENTITY_STATE = 0x102

CL_AMS_ERR_INVALID_ENTITY_LIST = 0x103

CL_AMS_ERR_ENTITY_NOT_ENABLED = 0x104

CL_AMS_ERR_BAD_CONFIG = 0x105

CL_AMS_ERR_INVALID_ARGS = 0x106

CL_AMS_ERR_INVALID_OPERATION = 0x107

CL_AMS_ERR_OPERATION_FAILED = 0x108

CL_AMS_ERR_SI_NOT_ASSIGNABLE = 0x109

CL_AMS_ERR_CSI_NOT_ASSIGNABLE = 0x10a

CL_AMS_ERR_UNMARSHALING_FAILED = 0x10b

def CL_AMS_RC(ERROR_CODE):
    return clCommonErrors.CL_RC(clCommon.eClCompIdT.CL_CID_AMS, ERROR_CODE)
