import sys
sys.path.append("..")

from common import clCommon, clCommonErrors

CL_CPM_ERR_OPERATION_NOT_ALLOWED = 0x100
CL_CPM_ERR_EO_UNREACHABLE = 0x101
CL_CPM_ERR_INVALID_ARGUMENTS = 0x102
CL_CPM_ERR_OPERATION_FAILED = 0x103
CL_CPM_ERR_FORWARDING_FAILED = 0x104
CL_CPM_ERR_OPERATION_IN_PROGRESS = 0x105
CL_CPM_ERR_INIT = 0x106
CL_CPM_ERR_BAD_OPERATION = 0x107
CL_CPM_ERR_EXIST = 0x108
CL_CPM_ERR_OPER_ABANDONED = 0x109

def CL_CPM_RC(ERROR_CODE):
    return clCommonErrors.CL_RC(clCommon.eClCompIdT.CL_CID_CPM, ERROR_CODE)
